{% set version = "0.4.0" %}
{% set python_min = "3.12" %}

package:
  name: fgmetric
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fgmetric/fgmetric-{{ version }}.tar.gz
  sha256: 77b6d5cfa9fd4d8f6ec9d25c25baaabafdb409a2692dc27517048ff23a9bc725

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage('fgmetric', max_pin="x.x") }}

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.11.4
    - xopen >=2.0.0

test:
  imports:
    - fgmetric
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/fgmetric/
  summary: Type-validated Python models for delimited data files.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msto
