{% set version = "0.2.0" %}
{% set python_min = "3.12" %}

package:
  name: fgmetric
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fgmetric/fgmetric-{{ version }}.tar.gz
  sha256: cf0ad030f0d4d3bf04cbe9d93326c2e544e8a2b3e8467b4810df35ebb666d7f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage('fgmetric', max_pin="x.x") }}

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.11.4

test:
  imports:
    - fgmetric
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/fgmetric/
  summary: Type-validated Python models for delimited data files.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msto
